---
output: 
  html_document:
    fig_caption: yes
    css: www/webstyles.css
    anchor_sections: FALSE
    includes: 
      in_header: "header_manual.html" 
      after_body: "footer.html"
    self_contained: yes
title: "NETN water summary"
params:
  park: MABI # 4-letter park code
  year_start: 2006 # first year of data
  year_current: 2023 # current year of data
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.pos = "h", warning = FALSE, message = FALSE)
```

```{r include = F, results = 'hide'}
library(tidyverse)
library(waterNETN)
library(leaflet)
library(grid)
library(gridExtra)
library(kableExtra)
#library(plotly)
```
```{r results = 'hide', cache = T, eval = F}
#importData(type = "zip", filepath = "C:/NETN/R_Dev/Water/data/NETN_Water_Data_Package_20240725.zip")
```

```{r }
# park = "ACAD"; yr_start = 2006; yr_current = 2023;
parkcode <- "ACAD" #child_env$park
# park = parkcode
# yr_start <- params$year_start
# yr_current <- params$year_current
# yr_prev <- yr_current - 1

site_df <- unique(getEvents(park = "ACAD", years = yr_current)[, c("SiteCode", "SiteName", "UnitCode", "UnitName", "SiteType")])
site_list <- unique(site_df$SiteCode)
park_name <- unique(site_df$UnitName)
site_name <- unique(site_df$SiteName)
lake_list <- unique(site_df$SiteCode[site_df$SiteType == "Lake"])
stream_list <- unique(site_df$SiteCode[site_df$SiteType == "Stream"])
eval_stream <- if(!is.null(stream_list)){TRUE} else {FALSE}
eval_lake <- if(!is.null(lake_list)){TRUE} else {FALSE}

# lake_df <- getSitesLake(park = "ACAD")[c("SiteCode", "TrophicType")]
# lake_eut <- unique(lake_df$SiteCode[lake_df$TrophicType == "EUTROPHIC"])
# lake_mes <- unique(lake_df$SiteCode[lake_df$TrophicType == "MESOTROPHIC"])
# lake_oli <- unique(lake_df$SiteCode[lake_df$TrophicType == "OLIGOTROPHIC"])
# 
# stream_df <- getSitesStream(park = "ACAD")[, c("SiteCode", "FisheryType")]
# stream_cold <- unique(stream_df$SiteCode[stream_df$FisheryType == "Coldwater"])
# stream_warm <- unique(stream_df$SiteCode[stream_df$FisheryType == "Warmwater"])

source("fake_bands_legend_code.R") # for legend called legg
```

## ACAD {.tabset}
### Lakes {.tabset}
<!-- Plots for lakes only -->
#### Water Quality  {.tabset}
```{r warning = FALSE, message = FALSE, results = 'asis', fig.height=9, fig.width=13}
for(i in seq_along(lake_list)){
  field_params = c("DO_mgL", "pH", "Temp_F", "SpCond_uScm", "SDepth_m")
  lab_params = c("TN_mgL", "TP_ugL", "ANC_ueqL")

  lakecode <- lake_list[[i]]
  sitename <- unique(site_df$SiteName[site_df$SiteCode==lakecode])
  sitecode <- unique(site_df$SiteCode[site_df$SiteCode==lakecode])
  
  cat("##### ", sitename, "{.tabset} \n\n")
  cat(paste0("###### Current Year (", yr_current, ")"))
  cat("\n\n")
  cat(paste0("<h1>Historic (", yr_start, " to ", yr_prev, ") vs. Current (", yr_current, ") Field Measurements</h1>\n\n"))

  <<waterbandp_chunk>>
  
  cat(paste0(
  "<p>",
  'The plots above show historic ranges for ', sitename, 
   ' based on the range of surface measurements (i.e. within 2m) collected from ',
   yr_start, ' to ', yr_prev, ' for each month. The outermost band represents the
   historic maximum and minimum value collected for each month.
   The second inner band represents the 95% range of historic values
   by month. The innermost band represents the 50% range of historic
   values by month. The points represent the most 
   recent measurements collected in ', yr_current, ' by month. 
   Water quality thresholds are derived from state surface water quality 
   standards. DO is dissolved oxygen. SpCond is specific conductance. Additional 
   information can be found in the "About the Data" tab.</p>\n\n'))
  cat("<br>\n")
  
  cat("\n\n")
  
  cat(paste0("<h1>Historic (", yr_start, " to ", yr_prev, ") vs. Current (", yr_current, ") Lab Chemistry</h1>\n\n"))

  <<waterbandn_chunk>>
  
  cat(paste0(
  "<p>",
  'The plots above show historic ranges for ', sitename, 
   ' based on the range of surface measurements (i.e. within 2m) collected from ',
   yr_start, ' to ', yr_prev, ' for each month. The outermost band represents the
   historic maximum and minimum value collected for each month.
   The second inner band represents the 95% range of historic values
   by month. The innermost band represents the 50% range of historic
   values by month. The points represent the most 
   recent measurements collected in ', yr_current, ' by month. 
   Water quality thresholds are derived from state surface water quality 
   standards. TN is total Nitrogen. TP is total Phosphorous. ANC is acid neutralizing capacity.
   Additional information can be found in the "About the Data" tab.</p>\n\n'))
  cat("\n\n")
  

  cat(paste0("###### Trends (", paste0(yr_start, ":", yr_current), ")"))
  cat("\n\n")
  cat(paste0("<h1>Trends in Field Measurements (", yr_start, " to ", yr_current, ")</h1>\n\n"))
  cat("\n\n")
  ptf <- plotTrend(site = sitecode, years = yr_start:yr_current, span = 0.9, 
            parameter = field_params, palette = c("#5AA7D7"), legend_position = "bottom")
  
  print(ptf)
  cat("\n\n")
  cat(paste0(
  "<p>",
  'The plots above show trends in field measurements for ', sitename, 
   ' collected withint 2m of the surface from ', yr_start, ' to ', yr_current, 
   ' for each month of data. Points represent monthly sample measurements. 
   Lines represent loess smoothed trends with span 0.9. 
   Water quality thresholds are derived from state surface water quality standards. 
   DO is dissolved oxygen. SpCond is specific conductance. Additional 
   information can be found in the "About the Data" tab.</p>\n\n'))
  cat("<br>\n")
  
  cat("\n\n")
  cat(paste0("<h1>Trends in Lab Chemistry (", yr_start, " to ", yr_current, ")</h1>\n\n"))
  cat("\n\n")
  ptl <- plotTrend(site = sitecode, years = yr_start:yr_current, span = 0.9, 
            parameter = lab_params, palette = c("#5AA7D7"), legend_position = "bottom")
  print(ptl)
  cat("\n\n")
  cat(paste0(
  "<p>",
  'The plots above show trends in lab chemistry for ', sitename, 
   ' collected withint 2m of the surface from ', yr_start, ' to ', yr_current, 
   ' for each month of data. Points represent monthly sample measurements. 
   Lines represent loess smoothed trends with span 0.9. 
   Water quality thresholds are derived from state surface water quality standards. 
   TN is total Nitrogen. TP is total Phosphorous. ANC is acid neutralizing capacity. Additional 
   information can be found in the "About the Data" tab.</p>\n\n'))
  cat("\n\n")
}
```
<br>

#### Water Quantity {.tabset}
```{r warning = F, message = FALSE, eval = eval_lake, results = 'asis', fig.height=5, fig.width=13}
for(i in seq_along(lake_list)){
  lakecode <- lake_list[[i]]
  sitename <- unique(site_df$SiteName[site_df$SiteCode==lakecode])
  sitecode <- unique(site_df$SiteCode[site_df$SiteCode==lakecode])
  cat("\n\n")
  cat("##### ", sitename, "{.tabset}")
  cat("\n\n")
  cat("###### Current Year (", yr_current, ")")
  cat("\n\n")
  cat(paste0("<h1>Historic (", yr_start, " to ", yr_prev, ") vs. Current (", yr_current, ") Lake Level </h1>\n\n"))

  wl_band <- plotWaterBands(site = lakecode, year_current = yr_current, 
                 years_historic = yr_start:yr_prev, parameter = "WaterLevel_Feet", 
                 threshold = F)

  blank <- rectGrob(gp = gpar(col = "white"))
  
  grid.arrange(wl_band, blank, blank, legg, blank, 
               heights = c(0.6, 0.2),
               widths = c(0.7, 0.15, 0.15),
               layout_matrix = rbind(c(1, 2, 3),
                                     c(4, 4, 5)),
               nrow = 2, ncol = 3)
  
  cat(paste0(
    "<p>",
    'Historic ranges in water level for ', sitename, 
     ' based on the range of measurements collected from ',
     yr_start, ' to ', yr_prev, ' for each month. The outermost band represents the
     historic maximum and minimum value collected for each month.
     The second inner band represents the 95% range of historic values
     by month. The innermost band represents the 50% range of historic
     values by month. The points represent the most 
     recent measurements collected in ', yr_current, ' by month. </p>\n\n'))
  cat("\n\n")

  cat(paste0("###### Trends (", paste0(yr_start, ":", yr_current), ")"))
  cat("\n\n")
  cat("<h1>Lake Water Level</h1>")
  cat("\n\n")
  p_wl <- plotTrend(park = parkcode, site = lakecode, months = 5:10,
            years = 2013:yr_current, parameter = "WaterLevel_Feet", span = 0.9, gridlines = "grid_x",
            legend_position = 'none', threshold = FALSE)
  print(p_wl)
  cat("\n\n")

  cat(paste0(
  "<p>",
  'Trends in water level for ', sitename, ' from 2013 to ', yr_current, 
  ' for each month. Points represent monthly sample measurements.', 
  'Lines represent loess smoothed trends with span 0.9.</p>\n\n'))
  cat("\n\n")
  cat("\n\n")
  <<climbar_l>>
  cat("\n\n")  
  cat("\n\n")
  cat(paste0(
  "<p>",
  'Trends in monthly precipitation from May to October for ', sitename, 
   ' from 2013 to ', yr_current, '.</p>\n\n'))
  cat("\n\n")
  }
```
<br>

#### Lake Profiles {.tabset}
```{r}
param_list <- c("DO_mgL", "Temp_F", "pH", "SpCond_uScm", "ChlA_EXO_ugL")#, "Turbidity_FNU")
param_name <- c("Dissolved Oxygen (mgL)", "Temperature (F)", "pH", "Specific Conductance (uScm)",
                "Chlorophyll A (ugL)")#, "Turbidity (FNU)")
palette_list <- c("RdYlBu", "RdYlBu", "RdYlBu", "RdYlBu", "RdYlBu")
palette_rev <- c(TRUE, FALSE, TRUE, FALSE, FALSE)
param_df <- data.frame(param = param_list, param_name = param_name, pal = palette_list, rev = palette_rev)
```

##### Summary of Current Year (`r yr_current`)

```{r results = 'asis', fig.height = 9, fig.width = 13}
for(i in seq_along(param_list)){
  param = param_df$param[[i]]
  pal = param_df$pal[param_df$param == param]
  rev = param_df$rev[param_df$param == param]
  param_name = param_df$param_name[param_df$param == param]

  <<prof_stat>>
}
```

##### Summary of Trends (`r paste0(yr_start, ":", yr_current)`) {.tabset}

```{r results = 'asis', fig.height = 9, fig.width = 13}
for(i in seq_along(lake_list)){
  sitecode = lake_list[[i]]
  cat("###### ", sitecode, "\n\n")
  for(j in seq_along(param_list)){
  param = param_df$param[[j]]
  pal = param_df$pal[param_df$param == param]
  rev = param_df$rev[param_df$param == param]
  param_name = param_df$param_name[param_df$param == param]
  
  <<prof_trend>>
    
  }
}
```


#### Sampling History {.tabset}
```{r}
samp_hist <- sumEvents(park = parkcode, site_type ='lake', years = yr_start:yr_current) |> 
  select(SiteName, param_type:Oct_cens) |> 
  arrange(SiteName, param_type, Parameter)

samp_tab <- 
  kable(samp_hist, format = 'html', align = c(rep("l", 3), rep("c", 13)),
        col.names = c("Site Name", "Param. Type", "Parameter", "Year Range",
                      "# Years Sampled", "May", "Jun", "Jul", "Aug", "Sep", "Oct",
                      "May cens.", "Jun cens.", "Jul cens.", "Aug cens.", "Sep cens.", "Oct cens.")) |> 
  kable_styling(fixed_thead = TRUE, bootstrap_options = c('condensed'), full_width = FALSE,
               position = 'left', font_size = 11) |> 
  collapse_rows(1:2, valign = 'top') 

samp_tab
```


<!-- Plots for streams only -->
### Streams {.tabset}
#### Water Quality  {.tabset}

```{r warning = FALSE, message = FALSE, results = 'asis', fig.height=9, fig.width=13}
for(i in seq_along(stream_list)){
  field_params = c("DO_mgL", "pH", "Temp_F", "SpCond_uScm")
  lab_params = c("TN_mgL", "TP_ugL", "ANC_ueqL")
  
  streamcode <- stream_list[[i]]
  sitename <- site_df$SiteName[site_df$SiteCode==streamcode]
  sitecode <- site_df$SiteCode[site_df$SiteCode==streamcode]
  cat("##### ", sitename, "{.tabset} \n\n")
  cat("\n\n")
  cat("###### Current Year (", yr_current, ")")
  cat("\n\n")
  cat(paste0("<h1>Historic (", yr_start, " to ", yr_prev, ") vs. Current (", yr_current, ") Field Measurements</h1>\n\n"))

  <<waterbandp_chunk>>
  
  cat(paste0(
  "<p>",
  'The plots above show historic ranges for ', sitename, 
   ' based on the range of surface measurements (i.e. within 2m) collected from ',
   yr_start, ' to ', yr_prev, ' for each month. The outermost band represents the
   historic maximum and minimum value collected for each month.
   The second inner band represents the 95% range of historic values
   by month. The innermost band represents the 50% range of historic
   values by month. The points represent the most 
   recent measurements collected in ', yr_current, ' by month. 
   Water quality thresholds are derived from state surface water quality 
   standards. DO is dissolved oxygen. SpCond is specific conductance. Additional 
   information can be found in the "About the Data" tab.</p>\n\n'))

  cat("\n\n")
  
  cat(paste0("<h1>Historic (", yr_start, " to ", yr_prev, ") vs. Current (", yr_current, ") Lab Chemistry</h1>\n\n"))

  <<waterbandn_chunk>>
  
  cat(paste0(
  "<p>",
  'The plots above show historic ranges for ', sitename, 
   ' based on the range of surface measurements (i.e. within 2m) collected from ',
   yr_start, ' to ', yr_prev, ' for each month. The outermost band represents the
   historic maximum and minimum value collected for each month.
   The second inner band represents the 95% range of historic values
   by month. The innermost band represents the 50% range of historic
   values by month. The points represent the most 
   recent measurements collected in ', yr_current, ' by month. 
   Water quality thresholds are derived from state surface water quality 
   standards. TN is total Nitrogen. TP is total Phosphorous. ANC is acid neutralizing capacity.
   Additional information can be found in the "About the Data" tab".</p>\n\n'))
  cat("\n\n")

  cat("###### Trends (", paste0(yr_start, ":", yr_current), ")")
  cat("\n\n")
  cat(paste0("<h1>Trends in Field Measurements (", yr_start, " to ", yr_current, ")</h1>\n\n"))
  cat("\n\n")
  ps_f <- plotTrend(site = sitecode, years = yr_start:yr_current, span = 0.9, 
                    parameter = field_params, palette = "#5AA7D7", legend_position = 'bottom')
  print(ps_f)
  cat("\n\n")
  cat(paste0("<p>Trends in field water quality parameters for ", sitename, " from ",
           yr_start, " to ", yr_current, ". Points represent monthly sample measurements.", 
           " Lines represent loess smoothed trends with span 0.9.</p>\n\n"))

  cat("\n\n")

  cat(paste0("<h1>Trends in Lab Chemistry (", yr_start, " to ", yr_current, ")</h1>\n\n"))
  cat("\n\n")
  ps_l <- plotTrend(site = sitecode, years = yr_start:yr_current, span = 0.9, 
                    parameter = lab_params, palette = "#5AA7D7", legend_position = "bottom")

  print(ps_l)
  cat("\n\n")
  cat(paste0("<p>Trends in lab chemistry water quality parameters ", sitename, " from ",
             yr_start, " to ", yr_current, ". Points represent monthly sample measurements.", 
             " Lines represent loess smoothed trends with span 0.9.</p>\n\n"))

  cat("\n\n")
}
```
<br>

#### Water Quantity {.tabset}
```{r warning = F, message = FALSE, eval = eval_stream, results = 'asis', fig.height=5, fig.width=13, cache = T}
for(i in seq_along(stream_list)){
  streamcode <- stream_list[[i]]
  sitename <- site_df$SiteName[site_df$SiteCode==streamcode]
  sitecode <- site_df$SiteCode[site_df$SiteCode==streamcode]
  cat("##### ", sitename, "{.tabset} \n\n")
  cat("\n\n")
  cat(paste0("###### Current Year (", yr_current, ")"))
  cat("\n\n")
  cat("<h1>Discharge vs. Precipitation</h1>")
  cat("\n\n")
  p_dis <- plotPrecipDischarge(site = sitecode, years = yr_current, palette = c("#5AA7D7", "black"))
  print(p_dis)
  cat("\n\n")
  cat(paste0("<p>Monthly discharge vs. Daily precipitation for ", yr_current, 
    " in ", sitename, ". Precipitation is shown as blue bars. Discharge is represented by a black '+'.</p>"))
  cat("\n\n")

  cat(paste0("###### Trends (", yr_start, ":", yr_current, ")"))
  cat("\n\n")
  cat("<h1>Discharge</h1>")
  cat("\n\n")
  p_dist <- plotTrend(park = parkcode, site = sitecode, years = yr_start:yr_current, parameter = "Discharge_cfs", 
            gridlines = "grid_x", months = 5:10, threshold = F, span = 0.9)
  print(p_dist)
  cat("\n\n")
  cat("\n\n")
    cat(paste0("<p>Trends in monthly discharge for ", yr_start, " to ", yr_current, 
    " in ", sitename, ". Points represent monthly samples.', 
  ' Lines represent loess smoothed trends with span 0.9.</p>"))
  cat("\n\n")
  
  <<climbar_s>>
  
  cat("\n\n")
  cat(paste0(
  "<p>",
  'Trends in monthly precipitation from May - October for ', sitename, 
   ' from ',  yr_start, ' to ', yr_current, '.</p>\n\n'))

  }
```

#### Sampling History
```{r}
samp_hist <- sumEvents(park = parkcode, site_type = "stream", years = yr_start:yr_current) |> 
  select(SiteName, param_type:Oct_cens) |> 
  arrange(SiteName, param_type, Parameter)

samp_tab <- 
  kable(samp_hist, format = 'html', align = c(rep("l", 3), rep("c", 13)),
        col.names = c("Site Name", "Param. Type", "Parameter", "Year Range",
                      "# Years Sampled", "May", "Jun", "Jul", "Aug", "Sep", "Oct",
                      "May cens.", "Jun cens.", "Jul cens.", "Aug cens.", "Sep cens.", "Oct cens.")) |> 
  kable_styling(fixed_thead = TRUE, bootstrap_options = c('condensed'), full_width = FALSE,
               position = 'left', font_size = 11) |> 
  collapse_rows(1:2, valign = 'top') 

samp_tab
```


### About the Sites
Click on the blue icons below to learn more about each site.

```{r out.width="80%", message=F}
NPSbasic <- "https://atlas-stg.geoplatform.gov/styles/v1/atlas-user/ck58pyquo009v01p99xebegr9/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoiYXRsYXMtdXNlciIsImEiOiJjazFmdGx2bjQwMDAwMG5wZmYwbmJwbmE2In0.lWXK2UexpXuyVitesLdwUg"

ESRIimagery <- "http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"

ESRItopo <- "http://services.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"

ESRINatGeo <- "http://services.arcgisonline.com/arcgis/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}"

bbox <- read.csv("boundboxes.csv") #lat/long coordinates and zoom level for each park 

# Find center coordinates of park box
long_cent <- mean(c(bbox$LongE[bbox$ParkCode == park], bbox$LongW[bbox$ParkCode == park]))
lat_cent <- mean(c(bbox$LatN[bbox$ParkCode == park], bbox$LatS[bbox$ParkCode == park]))

# Compile water sites dataframe with codes, names, lat/long coordinates, and site type
water_sites1 <- getSites(park = park)[,c("SiteCode", "SiteName", "SiteLatitude", "SiteLongitude",
                                         "site_type", "SiteDescription")]

years_active <- getEvents(park = parkcode, years = yr_start:yr_current, active = T) |> 
  select(UnitCode, SiteCode, year) |> group_by(UnitCode, SiteCode) |> 
  summarize(year_start = first(year), year_end = last(year), .groups = 'drop')


water_sites <- left_join(water_sites1, years_active, by = c("SiteCode"))
water_sites$Link = paste0("<a href='https://doimspp.sharepoint.com/sites/NETN_Photo_Viewer/Water_Quality_Site_Photos/", 
                     water_sites$Site, ".jpg' target='_blank'>Site Photo</a>")

# Legend html generator
# Source: https://stackoverflow.com/questions/47064921/leaflet-legend-for-addawesomemarkers-function-with-icons
# Icon library changed from font-awesome to ion

markerLegendHTML <- function(IconSet) {
    # Container div:
    legendHtml <- "<div style='padding: 10px; padding-bottom: 10px;'>
    <h4 style='padding-top:0; padding-bottom:10px; margin: 0; color:#555'> Legend </h4>" #legend title

    n <- 1
    # Add each icon for ion library icons:
    for (Icon in IconSet) {
        if (Icon[["library"]] == "ion") {
        legendHtml<- 
          paste0(legendHtml,
          # marker and marker label div
          "<div style='width: auto; height: 45px; display: flex; align-items: center;'>",
          # awesome marker div
          "<div style='position: relative; display: inline-block; width: 35px; height: 45px;' 
          class='awesome-marker-icon-", Icon[["markerColor"]]," awesome-marker'>",
          # add icons and set color
          # class='ion ion-waterdrop icon-white' selects the correct library, icon, and color
          "<i style='margin-left: 4px; margin-top: 11px' class= 'ion ion-",
            Icon[["icon"]]," icon-", Icon[["iconColor"]],"'></i>",
          "</div>", # close awesome marker div
          # legend label div - use name set in IconSet
          "<div style='position: relative; display: inline-block; margin-left: 8px;'>", 
            names(IconSet)[n] ,"</div>",
          "</div>") # close marker/marker label div    
        }
        n <- n + 1
    } 
    paste0(legendHtml, "</div>")
}

# Create list of icons to use in map
IconSet <- awesomeIconList(
  "stream" = makeAwesomeIcon(icon= 'waterdrop', markerColor = 'blue', iconColor = 'white', library = "ion"),
  "lake" = makeAwesomeIcon(icon= 'waterdrop', markerColor = 'cadetblue', iconColor = 'white', library = "ion")
)

# Create leaflet map
leaflet(height = 700) %>%
    # set default view of park
    setView(lng = long_cent,
            lat = lat_cent,
            zoom = bbox$Zoom[bbox$ParkCode == park]) %>%
    # setMaxBounds(lng1 = bbox[bbox$ParkCode == parkcode,]$LongE,
    #              lng2 = bbox[bbox$ParkCode == parkcode,]$LongW,
    #              lat1 = bbox[bbox$ParkCode == parkcode,]$LatN,
    #              lat2 = bbox[bbox$ParkCode == parkcode,]$LatS) %>%
    # add map tiles
    addTiles(group="Map", urlTemplate = NPSbasic, 
             options = providerTileOptions(minZoom = bbox$minZoom[bbox$ParkCode == park])) %>%
    addTiles(group="Imagery", urlTemplate = ESRIimagery) %>%
    addTiles(group="Topo", urlTemplate = ESRItopo) %>%
    addTiles(group="NatGeo", urlTemplate = ESRINatGeo) %>%
    # add button to control map tiles
    addLayersControl(map = ., baseGroups = c("Map","Imagery","Topo", "NatGeo"),
                     options = layersControlOptions(collapsed=T)) %>%
    # add site markers 
    addAwesomeMarkers(data = water_sites, ~SiteLongitude, ~SiteLatitude, 
                      icon = ~IconSet[site_type], #style markers based on site type
                      # label on mouseover
                      label=as.character(water_sites$SiteName),
                      # popup on click
                      popup = paste0("<b>", water_sites$SiteName, "</b><br>",
                                     "<b>Type: </b>", water_sites$site_type, "<br>",
                                     "<b>Sample Period: </b>", water_sites$year_start, "&ndash;",
                                     water_sites$year_end, "<br>",
                                     water_sites$SiteDescription, "<br>",
                                     water_sites$Link
                                     )
                      ) %>%
    # add legend
    addControl(markerLegendHTML(IconSet = IconSet), position = "bottomleft")

```

