---
output: 
  html_document:
    fig_caption: yes
    css: www/webstyles.css
    anchor_sections: FALSE
    includes: 
      in_header: "header_manual.html" 
      after_body: "footer.html"
    self_contained: yes
title: "NETN water summary"
params:
  year_start: 2006 # first year of data
  year_current: 2023 # current year of data
---
# {.tabset .tabset-pills}

```{r echo = F, include = F, cache = F}
knitr::opts_chunk$set(echo = FALSE, fig.pos = "h", warning = FALSE, message = FALSE)
# Create environment for rmds to pull params from
library(tidyverse)
library(waterNETN)
library(leaflet)
library(grid)
library(gridExtra)

yr_start <- params$year_start
yr_current <- params$year_current
yr_prev <- yr_current - 1
#park_list <- c("MIMA")

child_env <- new.env()
importData()
for(n in ls(VIEWS_WQ, all.names = TRUE)) assign(n, get(n, VIEWS_WQ), child_env)

child_env$yr_start <- yr_start
child_env$yr_current <- yr_current
child_env$yr_prev <- yr_prev
child_env$park_list <- c("MABI", "WEFA") # Not sure why I can't run for all the parks
```

<!-- Set up water band physical chunk that's iterated in park_level_summary -->
```{r waterbandp_chunk, warning = F, message = FALSE, eval = FALSE}
wbplot_DO <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "DO_mgL") 

wbplot_pH <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "pH")

wbplot_sc <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "SpCond_uScm")

wbplot_temp <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "Temp_C")

wbn_plot <- 
grid.arrange(wbplot_DO, wbplot_pH, wbplot_temp, wbplot_sc, legg, 
             layout_matrix = rbind(c(1, 2),
                                   c(3, 4),
                                   c(5, 5)),
             heights = c(0.5, 0.5,  0.25),
             nrow = 3, ncol = 2)

wbn_plot

```

<!-- Set up water band chemistry chunk that's iterated in park_level_summary -->

```{r waterbandn_chunk, warning = F, message = FALSE, eval = FALSE}
wbplot_TN <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "TN_mgL") 

wbplot_TP <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "TP_ugL")

wbplot_ANC <- 
tryCatch(plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "ANC_ueqL"),
    error = function(e){NULL})

wbplot_ChlA <- 
tryCatch(plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "ChlA_ugL"), 
    error = function(e){NULL})

wbp_plot <- 
if(exists("wbplot_ANC") & exists("wbplot_ChlA")){
  grid.arrange(wbplot_TN, wbplot_TP, wbplot_ANC, wbplot_ChlA, legg,
               layout_matrix = rbind(c(1, 2),
                                     c(3, 4),
                                     c(5, 5)),
               heights = c(0.5, 0.5,  0.25),
               nrow = 3, ncol = 2)
} else if(exists("wbplot_ANC")){
  grid.arrange(wbplot_TN, wbplot_TP, wbplot_ANC, legg,
               layout_matrix = rbind(c(1, 2),
                                     c(3, NA),
                                     c(4, 4)),
               heights = c(0.5, 0.5,  0.25),
               nrow = 3, ncol = 2)
} else if(exists("wbplot_ChlA")){
  grid.arrange(wbplot_TN, wbplot_TP, wbplot_ChlA, legg,
               layout_matrix = rbind(c(1, 2),
                                     c(3, NA),
                                     c(4, 4)),
               heights = c(0.5, 0.5,  0.25),
               nrow = 3, ncol = 2)
} else {
  grid.arrange(wbplot_TN, wbplot_TP, legg,
               layout_matrix = rbind(c(1, 2),
                                     c(3, 3),
               heights = c(0.9, 0.25),
               nrow = 2, ncol = 2))
}


```

```{r results = 'asis', include = F}
res <- lapply(seq_along(child_env$park_list), function(x){
  child_env$park = child_env$park_list[[x]]
  knitr::knit_child("park_level_summary.rmd", envir = child_env)
  #knitr::knit_child("About_tabs.Rmd", envir = child_env)
  
})
```
```{r results = 'asis'}
cat(unlist(res), sep = "\n\n")
```

```{r child = "About_tabs.Rmd", eval = T}

```

