---
output: 
  html_document:
    fig_caption: yes
    css: www/webstyles.css
    anchor_sections: FALSE
---

<!-- Set up water band physical chunk that's iterated in park_level_summary -->
```{r waterbandp_chunk, warning = F, message = FALSE, eval = FALSE}
wbplot_DO <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "DO_mgL") 

wbplot_pH <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "pH")

wbplot_sc <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "SpCond_uScm")

wbplot_temp <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "Temp_F")

wbn_plot <- 
grid.arrange(wbplot_DO, wbplot_pH, wbplot_temp, wbplot_sc, legg, 
             layout_matrix = rbind(c(1, 2),
                                   c(3, 4),
                                   c(5, 5)),
             heights = c(0.5, 0.5,  0.25),
             nrow = 3, ncol = 2)

wbn_plot

```

<!-- Set up water band chemistry chunk that's iterated in park_level_summary -->

```{r waterbandn_chunk, warning = F, message = FALSE, eval = FALSE}
wbplot_TN <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "TN_mgL") 

wbplot_TP <- 
plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "TP_ugL")

wbplot_ANC <- 
tryCatch(plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "ANC_ueqL"),
    error = function(e){NULL})

wbplot_ChlA <- 
tryCatch(plotWaterBands(site = sitecode, year_current = yr_current, 
               years_historic = yr_start:yr_prev, 
               parameter = "ChlA_ugL"), 
    error = function(e){NULL})

wbp_plot <- 
if(exists("wbplot_ANC") & exists("wbplot_ChlA")){
  grid.arrange(wbplot_TN, wbplot_TP, wbplot_ANC, wbplot_ChlA, legg,
               layout_matrix = rbind(c(1, 2),
                                     c(3, 4),
                                     c(5, 5)),
               heights = c(0.5, 0.5,  0.25),
               nrow = 3, ncol = 2)
} else if(exists("wbplot_ANC")){
  grid.arrange(wbplot_TN, wbplot_TP, wbplot_ANC, legg,
               layout_matrix = rbind(c(1, 2),
                                     c(3, NA),
                                     c(4, 4)),
               heights = c(0.5, 0.5,  0.25),
               nrow = 3, ncol = 2)
} else if(exists("wbplot_ChlA")){
  grid.arrange(wbplot_TN, wbplot_TP, wbplot_ChlA, legg,
               layout_matrix = rbind(c(1, 2),
                                     c(3, NA),
                                     c(4, 4)),
               heights = c(0.5, 0.5,  0.25),
               nrow = 3, ncol = 2)
} else {
  grid.arrange(wbplot_TN, wbplot_TP, legg,
               layout_matrix = rbind(c(1, 2),
                                     c(3, 3),
               heights = c(0.9, 0.25),
               nrow = 2, ncol = 2))
}


```

<!-- Lake Profile Code Chunk for status -->
```{r prof_stat, results = 'asis', eval = F}
cat(paste0("<details open><summary class = 'drop'>", param_name, "</summary>", "\n\n"))
cat("\n\n")
prof_splot <- plotLakeProfile(site = lake_list, years = yr_current, parameter = param, palette = pal, color_rev = rev)
print(prof_splot)
cat("\n\n")
cat(paste0("<p style='width:1280px;'>Depth profiles of ", param_name, " for ", yr_current, "</p>", "\n\n"))
cat("</details>", "\n\n")
```

<!-- Lake Profile Code Chunk for trends -->
```{r prof_trend, results = 'asis', eval = F}
cat(paste0("<details open><summary class = 'drop'>", param_name, "</summary>", "\n\n"))
sitename = site_df$SiteName[site_df$SiteCode==sitecode]
cat("\n\n")
prof_tplot <- plotLakeProfile(site = sitecode, years = yr_start:yr_current, parameter = param, 
                              palette = pal, color_rev = rev)
print(prof_tplot)
cat("\n\n")
cat(paste0("<p style='width:1280px;'>Depth profiles in ", sitename, " for ", param_name, " from ", yr_start, 
    " to ", yr_current, "</p>"))
cat("</details>", "\n\n")
```
